### ISSUE TITLE
[BUG] conda activation crashes standalone execution

### ISSUE THREAD

**Issue by francois-rozet** [JoeriHermans/awflow#3]
### Issue description

In the `standalone` backend on Unix systems, the `os.system(command)` used here

https://github.com/JoeriHermans/awflow/blob/1fcf255debfbc18d39a6b2baa387bbc85050209d/awflow/backends/standalone/executor.py#L53-L60

 actually calls `/bin/sh`. For some OS, like Ubuntu, `sh` links to `dash` which does not support the scripting features required by `conda` activations. This results in runtime errors like

```console
sh: 5: /home/username/miniconda3/envs/envname/etc/conda/activate.d/activate-binutils_linux-64.sh: Syntax error: "(" unexpected
```

### Proposed solution

A solution would be to change the shell with which the commands are called. This is possible thanks to the `subprocess` package. A good default would be `bash` as almost all Unix systems use it.

```python
    if node.tasks > 1:
        for task_index in range(node.tasks):
            task_command = command + ' ' + str(task_index)
            return_code = subprocess.call(task_command, shell=True, executable='/bin/bash')
    else:
        return_code = subprocess.call(command, shell=True, executable='/bin/bash')
```

One could also add a way to change this default. Additionally, wouldn't it be better to launch the tasks as background jobs for the standalone backend (simply add `&` at the end of the command) ?

**Comment by JoeriHermans** [comment]
Fixed in next version with breaking API changes. https://github.com/JoeriHermans/awflow/tree/dawgz
